title: Aljohn Niño A. Fornolles
logo: "/images/logo2.png?raw=true"
description: >
  3rd-year BSIT student at UC-Banilad Campus.
  Passionate about technology solutions.
  <a href="https://www.linkedin.com/in/aljohn-ni%C3%B1o-fornolles-330719205/" style="display: block; margin-top: 10px; color: #1da1f2; text-decoration: underline; cursor: pointer !important;">View My LinkedIn Profile</a>


